on: [push]
name: variable substitution in json

jobs:
build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
   
    with:
        files: 'employee.json'
    env:
        username: t
        password: ${{ secrets.PASSWORD }}
        url: https://github.com/${{github.repository}}
